# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-22 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=32)),
                ('read_num', models.IntegerField()),
                ('comment_num', models.IntegerField()),
                ('choices', models.CharField(choices=[('0', '行业新闻'), ('1', '最新技术'), ('2', ' 行业新闻'), ('3', '专题讲座')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=32)),
                ('book_type', models.CharField(choices=[(0, '跟老男孩学linux'), (1, '跟老男孩学python')], max_length=32)),
                ('author', models.CharField(max_length=32)),
                ('publisher', models.CharField(max_length=32)),
                ('pub_time', models.DateField()),
                ('initial_price', models.IntegerField()),
                ('discount_price', models.IntegerField()),
                ('book_size', models.IntegerField()),
                ('book_package', models.CharField(max_length=32)),
                ('is_taozhuang', models.BooleanField()),
                ('book_ISBN', models.CharField(max_length=32)),
                ('book_page_num', models.IntegerField()),
                ('image', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_info', models.TextField(max_length=64)),
                ('author_info', models.TextField(max_length=64)),
                ('category', models.TextField()),
                ('pre_introduction', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='校区')),
                ('address', models.CharField(blank=True, max_length=512, null=True, verbose_name='详细地址')),
            ],
        ),
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Linux', 'Linux中高级'), ('PythonFullStack', 'Python高级全栈开发')], max_length=64, verbose_name='班级名称')),
                ('semester', models.IntegerField(verbose_name='学期')),
                ('price', models.IntegerField(default=10000, verbose_name='学费')),
                ('memo', models.CharField(blank=True, max_length=100, null=True, verbose_name='开班详情')),
                ('start_date', models.DateField(verbose_name='开班日期')),
                ('graduate_date', models.DateField(blank=True, null=True, verbose_name='结业日期')),
                ('class_type', models.CharField(blank=True, choices=[('fulltime', '脱产班'), ('online', '网络班'), ('weekend', '周末班')], max_length=64, null=True, verbose_name='班额及类型')),
                ('status', models.CharField(choices=[('0', '报名中'), ('1', '已开班')], max_length=32)),
                ('campuses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Campus', verbose_name='校区')),
            ],
        ),
        migrations.CreateModel(
            name='classmate_resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[(0, '评价'), (1, 'offer'), (2, '笔记'), (3, '视频')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='学院')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, verbose_name='标题')),
                ('image', models.CharField(blank=True, max_length=64, null=True, verbose_name='缩略图')),
                ('avg_salary', models.IntegerField(blank=True, null=True, verbose_name='学完平均薪资')),
                ('period', models.CharField(blank=True, max_length=300, null=True, verbose_name='周期')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='学员报名后，请改为真实姓名', max_length=32, null=True, verbose_name='姓名')),
                ('sex', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], default='male', max_length=16, null=True, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, default=None, help_text='格式yyyy-mm-dd', null=True, verbose_name='出生日期')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='手机号')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('is_admin', models.BooleanField(default=0, verbose_name='管理员')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[(0, 'python讲师'), (1, 'linux讲师')], max_length=32)),
                ('edu', models.CharField(max_length=32)),
                ('salary', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Campus')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('position', models.CharField(max_length=32)),
                ('company', models.CharField(max_length=32)),
                ('sign_date', models.DateField()),
                ('reason', models.CharField(max_length=64)),
                ('why_us', models.CharField(max_length=64)),
                ('wishes', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('position', models.CharField(max_length=32)),
                ('photo', models.CharField(max_length=128)),
                ('introduction', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('av_type', models.CharField(choices=[('0', '公开课'), ('1', '职场窍门'), ('2', 'IT百科')], max_length=32)),
                ('study_num', models.IntegerField()),
                ('upload_date', models.DateField(max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.College')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('src', models.CharField(max_length=128)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Video')),
            ],
        ),
        migrations.AddField(
            model_name='classlist',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='repository.Teacher', verbose_name='老师'),
        ),
    ]
