# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='文章标题')),
                ('summary', models.CharField(max_length=256, verbose_name='文章摘要')),
                ('img', models.ImageField(upload_to='img/article/', verbose_name='显示图片')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='类别名称')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.Category', verbose_name='文章类别'),
        ),
        migrations.AddField(
            model_name='article',
            name='detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repository.ArticleDetail', verbose_name='文章详情'),
        ),
    ]
