# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 03:17
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20190723_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetail',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='文章详情'),
        ),
    ]
