# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20190723_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repository.ArticleDetail', verbose_name='文章详情'),
        ),
    ]
